### PR TITLE
Add installation instructions of prerequisites

### PR DESCRIPTION
**Pull request by izho1042**
Signed-off-by: Ian Zhou <ian.zhou@student.uts.edu.au>

- Add the installation procedures for the prerequisites to a separate page.
- Configure the `nav.yml` to make the above page accessible through side navigation.

### CODE REVIEW

**Comment by izho1042** [comment]
@strieflin Sorry for the mess I've created. I think it was the commit after rebase that ruined the GPG sign-off. I have double-checked the key for this commit with `git log --show-signature`. This one should be fine.

**Comment by strieflin** [comment]
Having some issues with Codacy SCA analysis ATM. Resolving this with Codacy support and will come back to this PR afterwards.

**Review by strieflin — APPROVED** [review]
LGTM

**Comment by strieflin** [comment]
> @strieflin Sorry for the mess I've created. I think it was the commit after rebase that ruined the GPG sign-off. I have double-checked the key for this commit with `git log --show-signature`. This one should be fine.

Don't mind. Things go wrong sometimes 💩.

**Comment by strieflin** [comment]
This PR is a "reincarnation" of #45.

**Comment by strieflin** [comment]
PR is merged 🎉! Thanks @izho1042 for contribution and welcome to the Carbyne Stack community.

**Pull request merged**
